version: '3.8'

services:
  db:
    image: postgres:15.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-db}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - .postgres-data:/var/lib/postgresql/data
